equinor/mercury

- api/src/entities/Multiflash.py
- api/src/tests/test_data/multiflash_input.json
- api/src/tests/unit/entities/test_multiflash.py
Component length is not necessary to instantiate Multiflash. This is removed, necessitating an update of the validator functions.
The test data we currently have has some components outside of the list of common.components.COMPONENT_IDS and therefore the validation of component_ids has to be turned off for the time being.
closes #29
> feat: updated validator functions for Multiflash

- api/Dockerfile
Updates the git hash after merging in libhg repo.
> ci: update githash for libhg

- web/src/components/feature/CalculateFluid.tsx
InputParameters in FluidPackage was rendered every time value was changed meaning the autocomplete pops up every time values are changed.
Moved inputparameters to output.
> fix: unnecessary rendering of autocomplete

- web/src/components/feature/PhaseTable.tsx
Need to have ratios in PhaseTable.
Added ratios.
Closes #43
> feat: add phase ratio to PhaseTable

- web/src/components/feature/FeedFlowInput.tsx
- web/src/components/feature/PhaseTable.tsx
- web/src/pages/Main.tsx
In order to compute the PhaseTable component, it is necessary to have a number for the feed flow (this is input, but not input to the Fortran code). The feed flow can be given as in Sm3/d or kg/d depending on which information the user has available, therefore there is a switch to change units.
Add a text field and a switch.
Closes #73
> feat: add feed unit input and switch

- web/src/components/feature/MoleTable.test.tsx
- web/src/components/feature/PhaseTable.test.tsx
- web/src/pages/Main.test.tsx
- web/src/setupTests.ts
Make tests cleaner.
Moves constants out of tests and into setuptest.ts
closes #81
Not sure if this is the best way to do it, but couldn't manage to get it working with globals as in the documentation without typescript errors.
> tests: move constants out of tests

- web/src/components/feature/CalculateFluid.tsx
User might have negative values to enter. This was not possible/very hard previously.
Remove value prop and substitute with placeholder.
Closes #104
> fix: make it possible to input negative numbers

- web/src/components/feature/CalculateFluid.tsx
This pull request is needed because calculations can take time and users can wonder if anything is happening
Adds a loading component to the button and disables it while calculations are running.
Closes #92
> feat: Add loading component

- web/src/components/feature/CalculateFluid.tsx
- web/src/components/feature/FeedFlowInput.tsx
- web/src/components/feature/PhaseTable.test.tsx
- web/src/components/feature/PhaseTable.tsx
- web/src/pages/Main.tsx
Feed flow is part of input.
Moved the switch from PhaseTable to a separate card below CalculateFluid.
Closes #95
> refactor: move feed flow switch below inputs

- web/src/components/feature/CalculateFluid.tsx
- web/src/components/feature/ComponentSelector.tsx
- web/src/components/feature/ComponentTable.tsx
- web/src/components/feature/FeedFlowInput.tsx
- web/src/components/feature/FluidDialog.tsx
- web/src/components/feature/PhaseTable.tsx
- web/src/pages/Main.tsx
- web/src/types.ts
This pull request is needed because gathering all exported types in one file makes it easier to get an overview of our types
Moves all exported types into a types file
> refactor: Create types file

- .github/workflows/deploy.yaml
- .pre-commit-config.yaml
- web/.eslintignore
- web/.eslintrc.json
- web/package.json
Disables eslint for running and building the web app. Also fixes eslint pre-commit hook to not show warning on ignored files, and to actually fix the code when run.
The reasoning is that a linting tool should not stop the app from building. The linting will still be checked in the tests.
Note: Open for debate on this one...
> ci: disable eslint for building

- web/package.json
- web/src/components/feature/CalculateFluid.tsx
- web/src/components/feature/ComponentSelector.tsx
- web/src/components/feature/ComponentTable.tsx
- web/src/components/feature/FeedFlowInput.tsx
- web/src/components/feature/FluidDialog.tsx
- web/src/pages/Main.tsx
Fixes a bug where only the 12 preSelected somponents where selectable in the ComponentSelector.
Also some refactor/minor changes:
- react hot reload now works on port 80 (WDS_SOCKET_PORT env var)
- disable run button when no components are selected
- disable save button when no packageName is set
- rename FluidDialog 'open' and 'onClose' to 'isOpen' and 'close'
- render some helpful text where the results will come
none, and resoles #118
> fix: only preSelected components was selectable

- web/src/components/common/Header.tsx
- web/src/components/feature/CalculationInput.tsx
- web/src/components/feature/FluidDialog.tsx
- web/src/pages/Main.tsx
Should be able to reuse saved packages
- Rename "CalculateFluid" component to "Input"
- Refactor stored packages to be a dict instead of a list with packages
- Load the package selected in the dropdown
none, but needed for #120
> feature: load saved package when selected

- web/src/components/feature/calculation_input/CalculationInput.tsx
- web/src/components/feature/calculation_input/FeedFlowInput.tsx
- web/src/components/feature/package_dialog/FluidDialog.tsx
- web/src/components/feature/results/PhaseTable.test.tsx
- web/src/components/feature/results/PhaseTable.tsx
- web/src/constants.ts
- web/src/pages/Main.tsx
- web/src/types.ts
Add support for conversion of feed units.
User can now convert between units and the conversion will happen in the UI. Unit switch is disabled until a composition feed is selected.
Closes #80
> feat: add conversion of feed flow between units

- web/src/components/feature/package_dialog/FluidDialog.tsx
This pull request is needed to reset dialog state when reopening
Adds isOpen to useEffect listening list
Closes #143
> fix: Reset package data on reopening dialog

- web/src/components/feature/calculation_input/CalculationInput.tsx
- web/src/components/feature/package_dialog/ComponentSelector.tsx
- web/src/components/feature/package_dialog/FluidDialog.tsx
This pull request is needed because we'd want the components with value to show in dialog when opening, not the defaults
- Dialog becomes more predictable if the entire dialog rerenders on opening. I've therefore wrapped it in a conditional and removed the isOpen input parameter
- I found a more intuitive solution the new/edit mode that allows me to remove editablePackage from CalculationInput. This also removes the danger of a race condition between isOpen and editablePackage
- Set autocomplete initials to depend on the componentRatios object
Closes #145
> fix: Rerender dialog on opening

- web/src/components/feature/package_dialog/ComponentSelector.tsx
- web/src/components/feature/package_dialog/ComponentTableSum.tsx
Checksum to see if the component inputs are in the desired range.
Adds a row with the sum of the components at the bottom of componentselector.
closes #148
> feat: add sum for component ratios

- web/src/components/feature/calculation_input/CalculationInput.tsx
- web/src/pages/Main.tsx
This pull request is needed because of....
Removes the unused usedComponentRatios state. The state was supposed to tell the moletable which feed ratios had been used in the calculation. Its use was removed in #134, as a result of the normalized ratios being returned by the API, but its declaration remained.
Cleanup after #130
> refactor: Remove unused usedComponentRatios state

- web/src/components/feature/package_dialog/ComponentTable.tsx
To accept decimalnumbers on format 0.01
Changed from Textfield to Input in ComponentTable. 
Removed toString(). 
#157
> fix: use Input in ComponentTable

- web/src/components/feature/results/PhaseTable.tsx
App crash for zero mercury.
Defaults zero mercury to array of zeros. Could be discussed how meaningful the output is and if it is perhaps better to give a warning about how mercury is zero and disallow computation?
Closes #142
> fix: app handles zero mercury

- web/src/components/feature/package_dialog/ComponentTable.tsx
Rename table header.
Just that.
Closes #94
> refactor: Rename ComponentSelector header to Mole Fractions

- web/src/components/feature/calculation_input/CalculationInput.tsx
User should be warned before any potential destructive actions
Prompt the user for a confirmation before overriding a FluidPackage with a new one
closes #161
> feature: warn user before overwriting existing package

- web/src/components/feature/package_dialog/ComponentSelector.tsx
- web/src/components/feature/package_dialog/FluidDialog.tsx
Making the app look better
- Bigger input fields for FluidPackage name and descsription
- Align ComponentSelector to right
closes #163
> fix: styling in fluidDialog. Align component input to right

- web/src/components/feature/results/MoleTable.tsx
Some users might want to do a quality control on the results, and need higher precision 
- Added a switch to control whether to format numbers in the MoleResult table
closes #186
> feature(web): toggle precision in Moletable

- web/src/components/common/Header.tsx
- web/src/components/feature/calculation_input/CalculationInput.tsx
- web/src/components/feature/package_dialog/FluidDialog.tsx
Users want to create fluid packages that are almost similar, templates are a solution for that.
Adds a dropdown for selecting packages as a template when creating a new, or editing a package
closes #188
> feature(web): be able to use existing packages as templates

- api/src/app.py
- api/src/features/component/component_feature.py
- api/src/features/metrics/metrics_feature.py
- api/src/features/multiflash/multiflash_feature.py
- radixconfig.yaml
PO wants to be able to see usage statistics of the tool
Adds a `/metrics` endpoint in according to https://www.radix.equinor.com/guides/monitoring/#metrics-visualisation.
NOTE: Consider this a test/proof-of-concept.
This is a very primitive light weight solution, the "count" metric type that is now exported might not be a good fit.
Would like to get this into radix and see how it looks.
related to #183  but not closing it yet...
> feature(api): expose metrics

- web/src/components/common/Header.tsx
Avoid both popovers being open at once, causing one to cover the other
Automatically closes the other popover when one of the popover opening buttons are clicked
> fix: Avoid both popovers open at once

- web/src/components/feature/package_dialog/ComponentSelector.tsx
- web/src/components/feature/package_dialog/ComponentTable.tsx
- web/src/components/feature/package_dialog/SaveButton.tsx
- web/src/components/feature/results/MoleTable.tsx
- web/src/pages/Main.tsx
- web/src/setupTests.ts
- web/src/types.ts
Eleni wants the order of the components table to be determined by the order they were added
Fixed by switching TComponentProperties from object to array
Closes #201
> fix: Fix component table order

- api/src/app.py
- api/src/tests/integration/features/component/test_component_feature.py
- api/src/tests/integration/features/health_check/test_health_check_feature.py
- api/src/tests/integration/features/multiflash/test_multiflash_feature.py
- api/src/tests/integration/features/whoami/test_whoami_feature.py
- nginx/sites-available/default.conf
- web/src/api/MercuryAPI.tsx
- web/src/api/generated/.openapi-generator/FILES
- web/src/api/generated/api.ts
- web/src/api/generated/api/component-api.ts
- web/src/api/generated/api/mercury-api.ts
- web/src/api/generated/api/metrics-api.ts
- web/src/api/generated/api/multiflash-api.ts
- web/src/api/generated/api/whoami-api.ts
- web/src/api/generated/models/multiflash-response.ts
- We are not using a versioned API strategy
- radix expects metrics to be served from "/metrics"
- Remove prefix for API
- Regenerate TS-Client
- Update paths in python unit tests
closes #238
> refactor: remove API prefix

- web/src/feature/package_dialog/ComponentSelector.tsx
- web/src/feature/package_dialog/ComponentTable.tsx
- web/src/feature/package_dialog/context/PackageDialogContext.tsx
- web/src/feature/package_dialog/context/reducer.tsx
This pull request is needed because of....
Removes the logic of validating ratios into the reducer
> refactor: Remove setAreRatioValid

- .github/workflows/publish.yaml
This pull request is needed because when fetch depth is not set, it is default 1. That one commit is then tagged as grafted, which messes up the version text we're showing on the website
Increase fetch-depth to 2 to remove the grafted tag from the relevant commit
Closes #247
> fix: Fix tag logging

- api/src/init.sh
Long running computations (~40-50 seconds) were killed by gunicorn due to it believing they were stalled.
After looking at several solutions, ended up with the simplest one: Increasing the timeout.
Closes #184
> fix: increase timeout for long computations

- web/src/constants.ts
- web/src/feature/calculation_input/CalculationInput.tsx
- web/src/feature/package_dialog/ComponentSelector.tsx
- web/src/feature/package_dialog/ComponentTable.tsx
- web/src/feature/package_dialog/ComponentTableSum.tsx
- web/src/feature/package_dialog/FluidDialog.tsx
- web/src/feature/package_dialog/SaveButton.tsx
- web/src/feature/package_dialog/TemplateSelector.tsx
- web/src/feature/package_dialog/context/PackageDialogContext.tsx
- web/src/feature/package_dialog/context/reducer.tsx
- web/src/types.ts
Eleni wants the component order to be constant after saving and reopening package
The fix turned out to be more complicated than I had thought, partly because our stored ratios might not have the same order as the selected components (imagine adding components in one order, and giving them value in another - then the comp order would differ). To fix this, I made the order and length of selectedComponents and ratios equal. I also made the code more robust, by moving logic into the reducer. 
**PLEASE TEST THIS** (I have tested a lot, but I still might have forgotten something)
Closes #259
> fix: Keep comp input order by using array

- web/src/feature/package_dialog/FluidDialog.tsx
- web/src/feature/package_dialog/SaveButton.tsx
- web/src/feature/package_dialog/TemplateSelector.tsx
This pull request is needed because the template could easily be misunderstood
- Increase dialog title text size
- Show only template when in new mode
- Rename save button to create/update
- Make template label more informative
Closes #262
> feature: Make template intuitive

- .github/CODEOWNERS
This pull request is needed because a PR needs the approval of all relevant code owners before we can merge it. Since RIkke and I are not code owners of the API currently, we can't approve dependabot issues for the API.
Makes all of us codeowners for everything
> fix: Same codeowners for all code

- api/src/common/components.py
- api/src/entities/ComponentResponse.py
- web/src/setupTests.ts
This pull request is needed because Eleni wants it
Rename all occurrences of Carbondioxide to Carbon Dioxide
Closes #293
> fix: Rename co2

- .github/workflows/on-tag.yaml
This pull request is needed because the old check of whether tag was on main was no longer working, causing our deployment to prod to fail
Removes test of whether tag is on main
> ci: remove main check from prod deploy workflow

- .github/workflows/deploy.yaml
- .gitignore
Radix is disabling "machine user" support
Use a Azure Service Principal with federated identity to authenticate with radix
none
> chore: migrate from radix machine token

- .github/dependabot.yml
Add groups to dependabot so that PRs created by dependabot is grouped together.
> ci: add dependency groups to dependabot

- api/src/config.py
Found some config variables that are unused in the project. No need for them to be there.
> chore: remove unsued MongoDB config vars

- api/Dockerfile
CI unable to use --no-dev flag
replace with --only=main
> fix: install poetry without dev

- .github/workflows/on-pull-request.yaml
Release please does not tigger a workflow run, which is required by branch protection
Make workflow trigger on reopen etc.
> ci: run workflow on release please pr updated

- nginx/nginx.conf
Radix reports critical usage on the proxy (nginx)
Reduce from 65535 -> 8192
> fix: reduce the number of worker connections
