equinor/mercury

web/.pnp.cjs, web/package.json, web/src/components/common/Card.tsx, web/yarn.lock
=> style: import colors from eds-tokens

.github/workflows/tests.yaml, web/package.json
=> feature(ci): enable web tests

.github/workflows/tests.yaml
Fixes caching issues.
Add python version to hash.
=> ci: try caching again after fix

web/src/components/feature/CalculateFluid.tsx, web/src/components/feature/FluidDialog.tsx, web/src/pages/Main.tsx
See checked tasks in #37
Closes #53
=> feat: fluid dialog

.pre-commit-config.yaml, api/src/entities/Multiflash.py, docker-compose.override.yml, web/generate-api-typescript-client.sh, web/src/App.tsx, web/src/api/MercuryAPI.tsx, web/src/components/common/DynamicTable.tsx, web/src/components/feature/MoleTable.test.tsx, web/src/components/feature/MoleTable.tsx, web/src/pages/Main.tsx
Users should be able to see the mole results from the calculations
- Added the "MoleTable"
- Added tests for the "MoleTable"
closes #23
=> feature: MoleTable and DynamicTable

README.md, web/src/App.tsx, web/src/authConfig.ts, web/src/components/feature/CalculateFluid.tsx, web/src/constants.ts, web/src/pages/Login.tsx, web/src/pages/Main.tsx
- Cleaner structure of the first few components of the web app
- Group "CalculateFluidDialog" with the "CalculateFluid" component. (Main.tsx was getting bussy)
- Separate Component for "Login checks" (Cleaner to keep out of page content)
=> refactor: restructure entry point for web app

web/src/components/feature/PhaseTable.test.tsx, web/src/components/feature/PhaseTable.tsx, web/src/pages/Main.tsx
Want to have a table to show results of phases.
Adds that table.
#62
=> feat: add PhaseTable

web/src/components/feature/ComponentSelector.tsx, web/src/components/feature/ComponentTable.tsx, web/src/pages/Main.tsx
Need to select components
Made component selector
=> feat: component for selecting components

web/src/components/common/DynamicTable.tsx, web/src/components/feature/MoleTable.tsx, web/src/components/feature/PhaseTable.tsx
This pull request is needed to make code easier to read and reuse
Rewrites the input format for DynamicTable to better match a table structure.
Closes #69
=> refactor: Change format of input to DynamicTable

web/src/components/feature/PhaseTable.test.tsx
Forgot to remove a prop from the test.
Removes the unused prop.
=> tests: remove unused prop in test

web/src/components/feature/MercuryWarning.tsx, web/src/pages/Main.tsx
This pull request is needed because we want users to get a warning if there are liquid mercury
Adds a warning banner if there is liquid mercury.
Closes #100
=> feat: Add warning if mercury phase exists

web/src/components/feature/CalculateFluid.tsx, web/src/components/feature/ComponentSelector.tsx, web/src/components/feature/ComponentTable.tsx, web/src/components/feature/FluidDialog.tsx, web/src/constants.ts, web/src/pages/Main.tsx
Multiflash computation should take values from ComponentTable
Adds states for collecting inputs from table and handle to update when save button is clicked. According to the figma sketches, the save button will be renamed to "ok" and/or replaced with "update package". 
Closes #110
=> feat: multiflash input update from FluidDialog

web/src/components/feature/MoleTable.test.tsx, web/src/components/feature/MoleTable.tsx, web/src/components/feature/PhaseTable.test.tsx, web/src/components/feature/PhaseTable.tsx, web/src/pages/Main.test.tsx, web/src/tableUtils.ts
Formatting in the tables are currently haywire.
Table entries are now formatted.
Closes #98, closes #99
=> fix: add precision formatting for tables

web/src/components/feature/FluidDialog.tsx
This pull request is needed to make the code easier to read and more consistent
Rewrites how we normalize component composition
=> refactor: Refactor ratio normalization

web/src/components/feature/calculation_input/CalculationInput.tsx, web/src/constants.ts
Give the user warning when the input is high or low, to ensure that the input is correct. 
Add warning on temperature and pressure if the input is to high or low. 
Write summary of what this pull request changes if needed.
=> feat: warning on temperature and pressure

web/src/components/feature/calculation_input/CalculationInput.tsx, web/src/components/feature/calculation_input/TempOrPressureInput.tsx
This pull request is needed because CalculationInput was getting too large
Creates a component for temp and pressure input and uses it in CalculationInput
=> refactor: Create component for temp/pressure input

web/src/components/feature/results/MoleTable.test.tsx, web/src/components/feature/results/MoleTable.tsx
Units are nice.
Add units to MoleTable
closes #93
=> feat: add units to MoleTable

web/src/components/feature/calculation_input/CalculationInput.tsx, web/src/components/feature/package_dialog/FluidDialog.tsx
This pull request is needed to allow users to edit existing packages in an intuitive way
Adds an edit button and logic to go with it.
Closes #24
=> feat: Add edit package button

web/src/components/common/Card.tsx
This pull request is needed because of styles are good
Fixed card widht
=> style: Increase CalculationInput width

web/src/components/feature/results/PhaseTable.test.tsx, web/src/components/feature/results/PhaseTable.tsx, web/src/tableUtils.ts
Get units on phase table.
Add units on phase table (mass concentration). 
#138
=> feat: add units to PhaseTable

web/src/components/feature/calculation_input/CalculationInput.tsx, web/src/components/feature/package_dialog/ComponentSelector.tsx, web/src/components/feature/package_dialog/FluidDialog.tsx, web/src/components/feature/package_dialog/SaveButton.tsx
This pull request is needed to make the fluid dialog look and behave as expected
- Fix button styling
- Fix header styling
- Add delete functionality
- Disable save when no changes
- Remove ratio when comp is deselected
Closes #37
=> Fluid dialog

web/src/components/feature/package_dialog/ComponentTableSum.tsx, web/src/tableUtils.ts
Precision on component sum was a little low.
Increased precision.
Closes #155
=> fix: increase precision on component sum

.github/workflows/publish.yaml
Updates formatting of version.txt for web and echo for api.
CI.
Related to #166
=> ci: update version.txt

.github/workflows/publish.yaml, api/src/init.sh, web/src/components/common/Header.tsx
Displays the current version number in the header.
Add axios call to read version.txt in public folder. 
Closes #166
Could not suppress the 404 in console if no version.txt is found. Should not be a problem for non-local setups as the version.txt exists in the docker-image and in ci.
=> feat: add version number to header

web/src/components/common/Header.tsx
Improved user experience
Reloads the page after clicking "Reset application"
closes #179
=> feature: reload page after resetting app for better feedback

web/src/components/common/Header.tsx
Nice to have
Adds a link to our github repo
Closes #224
=> feat: Add lnk to github repo

web/src/components/feature/calculation_input/CalculationInput.tsx
Important if calculation fails
Clear results when clicking run
Closes #221
=> fix: Clear results when clicking run

api/src/common/components.py
PO wanted more components.
Add them.
Closes #185
=> feat: add MEG and TEG components

web/src/components/feature/package_dialog/ComponentTable.tsx, web/src/components/feature/package_dialog/FluidDialog.tsx, web/src/components/feature/package_dialog/SaveButton.tsx
Packages can not have zero mercury
Not allowed to save packages with zero mercury.
Closes #178
=> feat: no more zero mercury packages

.github/workflows/on-push-main-branch.yaml, .github/workflows/on-tag.yaml, .github/workflows/publish.yaml
We want to move to prod
- Triggers on release tags on main only
- Fix bugs in workflow file
- Adds release tag to github image
Closes #244
=> ci: Fix release workflow

.github/workflows/publish.yaml
Bug in https://github.com/equinor/mercury/pull/245
Fixed how image-tags was parsed
=> ci: Fix bug in publish workflow

web/src/feature/calculation_input/CalculationInput.tsx, web/src/feature/calculation_input/TempOrPressureInput.tsx
Disable run button when invalid input on temperature or pressure.
Added a regex check and disable run button if input is not valid. 
closes #162 
closes #250
=> fix: added regex check on temp and pressure, disable run button

web/src/feature/package_dialog/FluidDialog.tsx
Add warning when deleting package. 
closes #254
=> feat: add warning when deleting package

web/src/feature/package_dialog/ComponentTable.tsx
This pull request is needed because of....
Write summary of what this pull request changes if needed.
=> style: Make input red if invalid

web/src/common/ErrorBoundary.tsx, web/src/common/Header.tsx, web/src/pages/Main.tsx
- Need an error boundary to inform users how to get out of a bad application state/handle errors
- Adds info on technical support email
- Adds one top level error boundary
closes #285
=> feature: create an ErrorBoundary

web/src/common/DynamicTable.tsx, web/src/feature/results/MoleTable.tsx, web/src/feature/results/PhaseTable.tsx
Eleni wants it
Add caption to result tables
Closes #261
=> feature: Add caption to result tables

api/poetry.lock, api/pyproject.toml
This pull request is needed because of security
Update all api dependencies. New fastapi needed httpx and adding it as an extra didn't help, so instead added it as dev-dependency
=> chore: Update api dependencies

README.md, web/public/version.txt, web/src/common/Header.tsx
Users of the web app need some information about the tool
- Adds the "Application info" to the "About"-popover
- Commit a "dummy" local version.txt file
- Update links to open in a new tab
closes #242
=> feature: add app readme in 'About'

.gitignore, README.md, web/src/common/Header.tsx
Some wanted changes to "About"
Minor changes to "About"
closes #347
=> fix: update about

runbook.md
Adds a simple runbook. Mainly for the log queries.
=> docs: add a minimal runbook

.pre-commit-config.yaml
This pull request is needed because of....
Write summary of what this pull request changes if needed.
=> ci: fix eslint failure

web/public/index.html
=> chore: update link to eds fonts

.github/workflows/create-release-pr.yaml
Don't want to stay at v1.0.0 forever
Write summary of what this pull request changes if needed.
=> ci: unlock release-please version

.github/dependabot.yml
Settings was wrong: "group" is not recognised while "groups" is.
Settings are unwronged.
=> ci: change group->groups

web/src/pages/Main.tsx
Eslint complaining about missing dependency.
=> fix(eslint): add appinsight as dependency

web/src/common/Header.tsx
=> feat: make help popover open on load

web/src/common/Card.tsx, web/src/common/DynamicTable.tsx
Typescript complained about some eds stuff. This fixes it.
=> fix: typescript errors with eds

.github/dependabot.yml
[Closes](https://github.com/equinor/team-hermes/issues/60?issue=equinor%7Cteam-hermes%7C62)
[Closes](https://github.com/equinor/team-hermes/issues/64?issue=equinor%7Cteam-hermes%7C65)
=> ci: added dependabot for github actions and docker
